name: stars-and-clounds

services: 
#proxy is combined with client build
  client: 
    build: client
    ports: 
      - 8443:8443
      - 80:80
      - 443:443
    networks:
      - backend
      - frontend

  apiv2: 
    build: apiv2
    env_file:
        - apiv2/.env.development
    expose: 
    - 3000
    deploy: 
      replicas: 3
    networks:
    - backend
    - deepback

  mysqldb: 
    build: mysql_db
    ports:
      - 3307:3306
    networks:
      - deepback

networks:
    frontend:
      driver: bridge
    backend:  
      driver: bridge
    deepback:
      driver: bridge
