upstream apis {
    server apiv1:4000;
}

server {
    listen 443 ssl;
    server_name 127.0.0.1;

    ssl_certificate conf.d/ssl/server.cert;
    ssl_certificate_key conf.d/ssl/server.key;
    
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;   
    
    location / {
        proxy_pass https://apis;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarder-For $proxy_add_x_forwarded_for;
                                                                                
    }
}

server {
    listen 80;
    server_name 127.0.0.1;
    
    location / {
        proxy_pass https://apis;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarder-For $proxy_add_x_forwarded_for;
 
    }
}
